variables:
  IMAGE_SKYPE_BOT: $CONTAINER_REGISTRY_PATH/skype-bot/skype-bot


before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


Build Skype Bot:
  stage: build
  script:
    - docker pull $IMAGE_SKYPE_BOT:latest || true
    - docker build --cache-from $IMAGE_SKYPE_BOT:latest -f Dockerfile -t $IMAGE_SKYPE_BOT:latest .
    - docker push $IMAGE_SKYPE_BOT:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - mlops-cluster

Deploy Skype BOT:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml --with-registry-auth skype-bot
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - mlops-cluster
