version: "3.9"

services:
  skype-bot:
    image: $CONTAINER_REGISTRY_PATH/skype-bot/skype-bot:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        # Hard limit
        limits:
          cpus: "1"
          memory: 100M
        # Soft limit
        reservations:
          cpus: "0.1"
          memory: 10M

      labels:
        - "traefik.http.routers.skype-bot.rule=Host(`ml.hosseinkhani.me`) && PathPrefix(`/skype-bot`)"
        - "traefik.http.services.skype-bot.loadbalancer.server.port=5000"
        - "traefik.http.middlewares.skype-bot-stripprefix.stripprefix.prefixes=/skype-bot, /skype-bot/"
        - "traefik.http.routers.skype-bot.middlewares=skype-bot-stripprefix"
    command: ["uvicorn", "main:app", "--root-path", "/skype-bot", "--host", "0.0.0.0", "--port", "5000", "--proxy-headers"]
    environment:
      USERNAME: ${SKYPE_BOT_USERNAME}
      PASSWORD: ${SKYPE_BOT_PASSWORD}
    networks:
      - traefik

networks:
  traefik:
    driver: overlay
    external: true
